server:
  port: 9001

  #方式二
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  #自定义前后缀
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

    #链路追踪（rg.springframework.web.client.ResourceAccessException: I/O error on POST request for ）
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web
