server:
  port: 9001

  #方式二
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  #自定义前后缀
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

    #链路追踪（rg.springframework.web.client.ResourceAccessException: I/O error on POST request for ）
  main:
    allow-bean-definition-overriding: true
#  zipkin:
#    base-url: http://192.168.200.100:9411/
#    sender:
#      type: web

#feign:
#  client:
#    config:
#      default:  #所有的@FeignClient 标注的feign客户端全部使用这个配置
#        connectTimeout: 1000
#        readTimeout: 5000
#        retryer: com.atguigu.gmall.common.retry.MyRetryer